export const GET_DOCTORLISTS_REQUEST = "GET_DOCTORLISTS_REQUEST";
export const GET_DOCTORLISTS_SUCCESS = "GET_DOCTORLISTS_SUCCESS";
export const GET_DOCTORLISTS_FAIL = "GET_DOCTORLISTS_FAIL";

export const GET_DOCTORLIST_DETAILS_REQUEST = "GET_DOCTORLIST_DETAILS_REQUEST";
export const GET_DOCTORLIST_DETAILS_SUCCESS = "GET_DOCTORLIST_DETAILS_SUCCESS";
export const GET_DOCTORLIST_DETAILS_FAIL = "GET_DOCTORLIST_DETAILS_FAIL";
export const GET_DOCTORLIST_DETAILS_RESET = "GET_DOCTORLIST_DETAILS_RESET";
